/* 365 daily cyber-awareness tips (Kerala Police Cyber Cell edition), Day 1 = Jan 1 .. Day 365 = Dec 31 */
window.CYBER_TIPS_365 = [
    "CyberWall Automated Triage: Forward suspected fraud links, message text, call scripts or APK files via WhatsApp (9497964163) or Telegram (@Cyber_wall_bot) for an instant AI-driven multi-layer threat check.",
    "CyberWall Multimodal Intake: Submit screenshots, voice notes, suspicious links, contact vCards or standalone APK files to the CyberWall validator for rapid triage.",
    "CyberWall Risk-Score Usage: Use CyberWall's risk signature and trust score only as localised operational guidance, then substantiate with institutional verification before any report or chargesheet.",
    "Cyberdome Inter-Agency Desk: Route cross-industry technical collaboration requests, custom tool development asks, and advanced research queries through Cyberdome's centre of excellence.",
    "Kid Glove Child-Safety Repository: Pull updated awareness modules, minor-safety intervention checklists and digital-risk profiles from the Kid Glove framework for school and community sessions.",
    "Pink Protection Patrol Liaison: Coordinate with Pink Protection patrol units when a cyber-harassment complaint from a woman involves a real-time stalking or physical-safety risk.",
    "Janamaithri Suraksha Cyber Liaison: Use the local Janamaithri Suraksha beat network to gather community-level leads on organised OTP/parcel-scam gangs operating in a locality.",
    "Vanitha Cell Case Referral: Refer cyber-harassment and morphed-image cases involving women complainants to the Vanitha Cell for coordinated counselling-cum-investigation handling.",
    "Kerala Police Citizen Portal Tracking: Cross-check a complainant's grievance status on the Kerala Police Citizen Portal before re-recording a statement already logged online.",
    "District Cyber Helpdesk Single-Window: Direct walk-in complainants to the district Cyber Helpdesk for same-day preliminary triage before a full FIR is registered.",
    "POCSO e-Box Anonymous Reporting: Monitor the POCSO e-Box channel for anonymous tip-offs on child sexual abuse material circulating on local networks or devices.",
    "Cyberdome Capacity-Building Track: Enrol investigating officers in Cyberdome's periodic capacity-building and CTF-style training tracks to stay current on emerging fraud patterns.",
    "Cyber Dome Darknet Monitoring Cell: Route suspected darknet-marketplace leads (contraband, stolen-data sales) to the dedicated Cyber Dome monitoring cell for specialised handling.",
    "Student Police Cadet Digital Hygiene Outreach: Use Student Police Cadet volunteers to run basic digital-hygiene outreach sessions in schools, feeding early-warning trends back to the cyber cell.",
    "Social Media Monitoring Cell Escalation: Escalate fast-spreading rumour or fake-news content with public-order implications to the Social Media Monitoring Cell the same day it is detected.",
    "1930 Golden-Hour Financial Triage: Call the national 1930 helpline within the golden hour of a financial cyber incident so the banking system can flag and freeze the layered funds trail.",
    "NCRP Report-Suspect Module: Log malicious URLs, fraudulent WhatsApp/Telegram business handles, phishing email headers and bulk-SMS originators in the NCRP Report Suspect module.",
    "I4C Suspect Registry Cross-Check: Cross-check unknown mobile numbers, email addresses, bank accounts and UPI IDs against the I4C Suspect Repository before closing a preliminary enquiry.",
    "Samanvaya Inter-State Dashboard: Use the Samanvaya dashboard to map cross-border case linkages, common mule-account clusters and coordinate with other state LEAs on the same syndicate.",
    "CyTrain LMS Certification: Complete the relevant CyTrain e-learning modules and mandatory certification before independently handling NCRP escalations or evidentiary submissions.",
    "National Cyber Threat Intel Sharing: Subscribe your unit to the national cyber threat intelligence bulletins to stay ahead of newly reported fraud campaigns and malicious infrastructure.",
    "CCPWC Scheme Utilisation: Utilise CCPWC (Cyber Crime Prevention against Women & Children) scheme funds for forensic kits, training and dedicated women/child cybercrime desks as per the sanctioned plan.",
    "CFCFRMS Financial Fraud Tracking: Track a financial-fraud complaint's fund-freeze status through the Citizen Financial Cyber Fraud Reporting and Management System dashboard.",
    "CCTNS Repeat-Offender Cross-Reference: Cross-reference an accused's mobile number, email or bank account against CCTNS FIR history to identify repeat cyber-offenders across districts.",
    "ICJS Cross-Database Verification: Query the Interoperable Criminal Justice System to check for a suspect's parallel proceedings across police, prosecution, prisons and forensic databases.",
    "NAFIS Latent Fingerprint Query: Submit latent prints lifted from seized devices, SIM trays or cash-mule handover points to NAFIS for a pan-India biometric match.",
    "I4C Volunteer Programme Vetting: Vet and route promising leads from registered Cyber Crime Volunteers through the prescribed verification workflow before acting on them.",
    "NCFL Advanced Exhibit Referral: Refer exhibits requiring advanced chip-off, decryption or GPU-cluster password recovery to the National Cyber Forensic Laboratory rather than local FSL queues.",
    "e-Prosecution / e-Courts Integration: Upload finalised cyber chargesheets and supporting digital-evidence certificates through the e-Prosecution portal for e-Courts synchronisation.",
    "1930 IVR Menu Familiarisation: Familiarise front-desk staff with the 1930 IVR menu structure so complainants are guided to the correct fraud-category queue without delay.",
    "Chakshu Fraud Submission: Log active spoofed-call vectors, phishing SMS patterns and fake customer-care WhatsApp accounts through the Sanchar Saathi Chakshu module for telecom-side action.",
    "TAFCOP Mobile Connection Audit: Check the Sanchar Saathi TAFCOP module to identify SIM connections fraudulently issued against a victim's identity for use in a case.",
    "Know-Your-Mobile IMEI Status: Use the Sanchar Saathi 'Know Your Mobile' feature to check whether a seized handset's IMEI is already flagged lost, stolen or duplicated.",
    "CEIR Stolen-Device Blocking: Submit a stolen or lost handset's IMEI to CEIR (Central Equipment Identity Register) for cross-operator blocking as soon as the loss is confirmed.",
    "TCCCPR Header Verification: Verify a suspicious bulk-SMS or promotional header against the TRAI TCCCPR registered-header list to confirm if the sender entity is genuine.",
    "CDR / CAF Requisition Protocol: Route Call Detail Record and Customer Application Form requests to the operator's nodal officer using the prescribed legal requisition format and case reference.",
    "Port-Out / SIM-Swap Detection: Request the operator's port-out and SIM-replacement logs when a victim reports sudden loss of mobile network coincident with OTP-based account takeover.",
    "IRSF Flagged Number Check: Cross-check inbound premium or international numbers involved in missed-call/callback fraud against known International Revenue Share Fraud number ranges.",
    "DND Registry Cross-Check: Cross-check a harassment complainant's DND registration status when unsolicited commercial calls are cited as part of a harassment pattern.",
    "Telecom Nodal Officer Escalation Matrix: Maintain an updated escalation contact sheet for each operator's law-enforcement nodal officer to speed up urgent CDR or tower-dump requests.",
    "BSA Section 63 Certificate: Attach a Section 63 Bharatiya Sakshya Adhiniyam certificate (successor to Evidence Act Section 65B) to every electronic record tendered as secondary evidence.",
    "BNSS Section 94 Document Summons: Use a Section 94 BNSS summons (successor to CrPC Section 91) when requisitioning documents, CDRs or digital records from a person or entity not under arrest.",
    "BNSS Section 35(3) Notice of Appearance: Issue a Section 35(3) BNSS notice (successor to CrPC Section 41A) instead of arrest where the offence does not warrant custodial interrogation at the first instance.",
    "Digital Search & Seizure Protocol: Follow the standard digital search protocol \u2014 photograph the scene, note device state (on/off/locked), and seize with a detailed panchnama before disconnecting power.",
    "Chain-of-Custody Documentation: Record every hand-off of a digital exhibit \u2014 from seizure, to FSL submission, to court production \u2014 on a single continuous chain-of-custody form.",
    "Mutual Legal Assistance Treaty Routing: Route requests for data held by foreign-headquartered platforms through the MLAT channel via the Ministry of Home Affairs where informal requests are declined.",
    "Emergency Data Preservation Request: Send an emergency disclosure/preservation request directly to major platforms (via their law-enforcement portals) to freeze account data pending a formal legal process.",
    "Section 65B/63 Certificate for CCTV: Obtain a proper certifying statement from the CCTV system administrator when tendering DVR/NVR footage, naming the device, export method and hash.",
    "Transit Remand for Cyber Cases: Apply for transit remand promptly when an accused arrested in one state is wanted in a Kerala cyber case, to avoid custody lapses during inter-state transfer.",
    "Provisional Attachment of Mule Funds: Initiate provisional attachment proceedings for funds traced to mule accounts before they are further layered or withdrawn.",
    "Cross-Jurisdiction FIR Transfer: Apply for CCTNS-based FIR transfer or clubbing when the same syndicate is implicated in cases registered across multiple Kerala districts.",
    "Search Warrant vs Consent Search: Distinguish clearly between a consent-based device inspection and a warrant-backed search \u2014 record consent in writing wherever obtained instead of assuming implied consent.",
    "Victim Statement Recording Standards: Record a cyber-fraud victim's statement with exact timestamps, transaction references and screenshots annexed as dated exhibits, not paraphrased summaries.",
    "Expert Witness Deposition Preparation: Brief the forensic expert before deposition on the exact exhibits, hash values and tools referenced in the report to ensure consistent courtroom testimony.",
    "Juvenile Accused Handling in Cyber Cases: Apply Juvenile Justice Act safeguards immediately on establishing a suspect's age is below 18, routing the matter to the Juvenile Justice Board.",
    "Data Localisation Compliance Checks: Verify whether a service provider is bound by data-localisation requirements before assuming Indian server data will be produced without an MLAT.",
    "Search Warrant for Cloud-Hosted Evidence: Frame search warrants for cloud-hosted evidence to name the account/service precisely, since a warrant for a physical premise does not automatically cover remote cloud data.",
    "Compounding and Settlement Limits in Cyber Offences: Confirm which specific offence sections in a cyber case are compoundable before entertaining any settlement application between parties.",
    "Video-Conferencing Deposition Protocol: Use the court-approved video-conferencing SOP when recording a witness or victim statement remotely, with proper identity verification on record.",
    "Case Diary Digital-Evidence Cross-Referencing: Cross-reference every digital exhibit number in the case diary narrative so the trial court can trace each factual claim to its supporting exhibit.",
    "SHA-256 Acquisition Hashing: Compute a SHA-256 hash for every exhibit immediately upon acquisition, before any analysis, to establish a mathematically provable integrity baseline.",
    "Write-Blocker Enforced Imaging: Always image storage media through a verified hardware or software write-blocker before any examination step touches the original.",
    "Forensic Image Verification Pairing: Generate and store both MD5 and SHA-256 hashes for every forensic image, verifying both after each copy operation.",
    "Bit-for-Bit Working-Copy Discipline: Perform all analysis exclusively on a verified working copy, never on the original exhibit or its sole forensic image.",
    "Evidence Custody Log Standardisation: Use a standard custody-log template capturing exhibit ID, hash, handler, timestamp and purpose for every access event across the case lifecycle.",
    "FSL Submission Format Compliance: Format digital exhibit submissions to FSL exactly per the prescribed forwarding-letter template, including hash values and the specific examination sought.",
    "Screenshot Certification Standard: Certify screenshots tendered as evidence with capture date, source URL/app, device used and the officer's signed statement of authenticity.",
    "Cloud Evidence Preservation Letters: Send a dated preservation letter to the relevant cloud/email/social platform the moment cloud-stored evidence is identified as relevant.",
    "Video Evidence Frame Extraction Standard: Extract key frames from video evidence at native resolution, never from a re-recorded or re-compressed screen capture.",
    "Report Standard: Tool Version Logging: Log the exact forensic tool name and version used for every extraction step in the final report, not just the tool's generic name.",
    "Metadata Preservation on File Transfer: Transfer evidentiary files using methods that preserve original filesystem timestamps and metadata rather than simple drag-and-drop copies that reset them.",
    "Redundant Backup of Case Exhibits: Maintain at least one offline, access-controlled backup of every digital case exhibit separate from the working investigation system.",
    "Report Standard: Chain-of-Reasoning Narrative: Write forensic reports as a chain of reasoning \u2014 artefact found, tool used, interpretation, conclusion \u2014 rather than a bare list of findings.",
    "Digital Signature Verification on Documents: Verify the digital signature certificate chain on any digitally signed document tendered as evidence, not just its visual signature block.",
    "Exhibit Numbering Consistency: Assign and use one consistent exhibit numbering scheme across the case diary, forensic report and chargesheet to prevent cross-reference confusion.",
    "Audio Evidence Authentication Standard: Subject disputed audio recordings to spectral and ELA-style authentication checks before relying on them as primary evidence.",
    "Report Standard: Negative Findings Documentation: Document explicitly when an expected artefact is NOT found (e.g., no deletion traces), not just positive findings.",
    "Multi-Examiner Peer Review: Route high-value or contested exhibits through a second examiner's peer review before the report is finalised and signed.",
    "Evidence Room Environmental Controls: Store seized electronic media in anti-static, temperature-controlled conditions to prevent physical degradation before analysis is complete.",
    "Report Standard: Plain-Language Summary: Prepare a one-page plain-language summary alongside the full technical forensic report for use by the investigating officer and prosecutor.",
    "Prefetch Execution Timeline: Parse Windows Prefetch (.pf) files to reconstruct a timeline of which executables ran on a seized machine and how often.",
    "Amcache.hve Program Execution: Extract Amcache.hve entries to identify programs that were executed or merely installed, including their original file paths and hashes.",
    "Shellbags Folder Access History: Parse Shellbags registry structures to reconstruct which folders \u2014 including on removable or now-disconnected drives \u2014 a user browsed.",
    "Jump Lists Recent-File Tracking: Examine Jump List files (AutomaticDestinations/CustomDestinations) to recover recently accessed files per application, even after the file itself is deleted.",
    "LNK File Metadata Extraction: Extract embedded metadata from .lnk shortcut files to recover the source machine's volume serial number, MAC address and original file path.",
    "$MFT Master File Table Carving: Carve the NTFS $MFT to recover file names, timestamps and even content fragments for files that have since been deleted.",
    "$LogFile / $UsnJrnl Change Journal: Parse the NTFS $UsnJrnl (USN Journal) to reconstruct a granular timeline of file creation, renaming and deletion events.",
    "Windows Event Log 4624/4625 Logon Analysis: Correlate Event IDs 4624 (successful logon) and 4625 (failed logon) to establish who was logged in during the window of an incident.",
    "Windows Event Log 1102 Clearance Detection: Check for Event ID 1102 to detect deliberate clearing of the Security event log, itself a strong indicator of anti-forensic intent.",
    "Registry RunMRU Command History: Extract RunMRU registry values to recover a history of commands typed into the Windows Run dialog box.",
    "PowerShell ConsoleHost History: Recover the ConsoleHost_history.txt file per user profile to reconstruct commands executed in PowerShell sessions.",
    "Windows Timeline / ActivitiesCache.db: Query ActivitiesCache.db to recover a cross-application activity timeline including app usage and some document access events.",
    "Volume Shadow Copy Recovery: Mount available Volume Shadow Copies to recover earlier states of files that have since been modified or deleted.",
    "Recycle Bin $I/$R Artifact Pairing: Pair $I (metadata) and $R (content) Recycle Bin artefacts to recover original file paths, deletion timestamps and content for deleted files.",
    "Browser SQLite History Extraction: Extract browsing history, downloads and form-autofill data directly from browser SQLite databases rather than relying on the in-app history view.",
    "Browser Cache Carving for Deleted Web Content: Carve cached web objects from browser cache folders to recover images or pages a user viewed even after browser history was cleared.",
    "Windows Search Index (Windows.edb) Mining: Mine the Windows Search index database to recover indexed file names and content snippets, including from since-deleted files.",
    "Thumbnail Cache (thumbcache.db) Recovery: Recover thumbnail images from thumbcache.db files to reconstruct evidence of images that once existed on the system, even after deletion.",
    "Sticky Notes / StickyNotes.snt Extraction: Extract content from the Sticky Notes database file, which can retain passwords, account details or plans a user jotted down.",
    "Windows Credential Manager Vault Analysis: Enumerate stored credentials in Windows Credential Manager to identify accounts and services the suspect actively accessed from that machine.",
    "BitLocker Recovery Key Retrieval: Check the suspect's Microsoft account or Active Directory for an escrowed BitLocker recovery key before attempting brute-force decryption.",
    "Windows Registry UserAssist Decoding: Decode ROT13-obfuscated UserAssist registry entries to recover a count and last-run time for GUI applications launched by a specific user.",
    "Print Spooler .SHD/.SPL Artifact Recovery: Recover residual .SHD/.SPL print spooler files to reconstruct evidence of documents printed from a seized machine.",
    "Windows Prefetch Hash Path Validation: Cross-validate a Prefetch entry's embedded path hash against the actual binary path to detect renamed or relocated malicious executables.",
    "Scheduled Tasks Persistence Audit: Enumerate Scheduled Tasks XML definitions to identify unauthorised persistence mechanisms configured for malware or remote-access tools.",
    "Services Registry Hive Persistence Check: Review the SYSTEM registry hive's Services key for suspicious service entries configured to auto-start with elevated privileges.",
    "Windows Defender Detection History Review: Pull Windows Defender's detection history and quarantine folder to identify malware the built-in AV already flagged before your examination began.",
    "Alternate Data Streams (ADS) Detection: Scan NTFS files for Alternate Data Streams, a technique sometimes used to hide payloads or mark-of-the-web bypass data.",
    "Windows Hibernation File (hiberfil.sys) Memory Carving: Carve the hibernation file for memory artefacts equivalent to a point-in-time RAM capture from when the machine last hibernated.",
    "Pagefile.sys String Carving: Run targeted string searches against pagefile.sys to recover fragments of passwords, chat text or URLs that transited system memory.",
    "Windows Notification Database (wpndatabase.db) Review: Extract historical notification content from wpndatabase.db, which can retain message previews even after the source app's data is cleared.",
    "Cortana / Search History Cache Review: Review Cortana and Windows Search history caches for search queries that reveal user intent before or after an incident.",
    "Windows Firewall Log Correlation: Enable and later correlate Windows Firewall logs with network capture data to confirm which local process initiated a suspicious outbound connection.",
    "Recent Files (Recent Items) Shortcut Analysis: Analyse the Recent Items folder's shortcut files to build a fast, low-effort timeline of recently opened documents.",
    "System Restore Point Registry Snapshot Comparison: Compare registry hive snapshots captured in different System Restore points to detect when a specific configuration change occurred.",
    "Windows Update History Timestamp Correlation: Correlate Windows Update install timestamps against the incident timeline to rule out or confirm a patch-related explanation for a system change.",
    "Sysmon Event Log Deep-Dive (if installed): Where Sysmon was pre-installed, mine its detailed process-creation and network-connection events for a far richer timeline than default logs provide.",
    "Windows Search Query History via Cortana Cache: Recover local search-query history cached by the OS search subsystem to corroborate what the user was actively looking for.",
    "Explorer Typed Paths (TypedPaths) Registry Key: Extract the TypedPaths registry key to recover file/folder paths a user manually typed into Windows Explorer's address bar.",
    "Windows Prefetch Volume Information Cross-Check: Cross-check volume information embedded in Prefetch files against the seized drive's actual volume serial to detect drive-swap attempts.",
    "CGNAT Subscriber Resolution: Request upstream ISP CGNAT logs using the exact combination of destination public IP, timestamp and source port to resolve an individual subscriber behind shared IP pools.",
    "WHOIS / RDAP Domain Attribution: Query official RDAP endpoints (successor to legacy WHOIS) for domain registration dates, registrar and nameserver history on a phishing domain.",
    "BGP / ASN Hosting Attribution: Resolve a malicious server's IP to its Autonomous System Number to identify the hosting provider and jurisdiction for a legal request.",
    "PCAP Full-Packet Capture Analysis: Analyse full-packet captures around the incident window to reconstruct exact payloads exchanged, not just connection metadata.",
    "DNS Query Log Correlation: Correlate a suspect device's DNS query logs against known malicious domain lists to establish contact even where the connection itself wasn't captured.",
    "VPN / Proxy Exit-Node Identification: Identify whether an attacking IP belongs to a known commercial VPN or proxy exit-node range before requesting logs from the apparent ISP.",
    "Tor Exit-Node Cross-Referencing: Cross-reference a connecting IP against public Tor exit-node lists to correctly identify anonymised traffic rather than misattributing it to an innocent third party.",
    "NAT Port-Mapping Log Requests: Request NAT/port-mapping logs from an ISP or enterprise network administrator to map an internal private IP to the specific device behind a shared public IP.",
    "Firewall / IDS Alert Timeline Reconstruction: Reconstruct an attack timeline from firewall and intrusion-detection alerts to establish the sequence of reconnaissance, exploitation and exfiltration.",
    "Netflow / Traffic-Volume Analysis: Analyse Netflow records for unusual traffic-volume spikes that indicate data exfiltration even when payload content isn't captured.",
    "Man-in-the-Middle Certificate Anomaly Detection: Check for unexpected or self-signed TLS certificates on a victim's device to detect a possible man-in-the-middle interception.",
    "Router/Modem Syslog Extraction: Extract syslog data from a victim's or suspect's home router to establish which devices were connected to the network during the incident window.",
    "Public Wi-Fi Access-Point Log Requests: Request access-point association logs from a public Wi-Fi provider (caf\u00e9, mall, transit hub) to place a suspect device at a location at a given time.",
    "Email Header 'Received' Chain Analysis: Trace the full chain of 'Received' headers in a phishing email to identify the originating mail server IP before it passed through legitimate relays.",
    "SMTP Server Abuse-Report Routing: Route spam/phishing-campaign evidence to the sending mail server's abuse contact identified via its IP's ASN registration.",
    "Load-Balancer / CDN IP Attribution Caveat: Recognise when a resolved IP belongs to a CDN or load balancer (e.g., shared cloud front-end) rather than the actual origin server hosting malicious content.",
    "Reverse DNS (PTR) Record Verification: Check the reverse DNS PTR record of a suspicious IP as a quick sanity check on whether it matches its claimed hosting provider or organisation.",
    "SSL/TLS Certificate Transparency Log Search: Search Certificate Transparency logs to discover all domains a phishing operation has registered certificates for, revealing related infrastructure.",
    "Autonomous Botnet C2 Beacon Pattern Analysis: Identify periodic beacon patterns in network logs that indicate malware checking in with a command-and-control server.",
    "Public Cloud Storage Bucket Exposure Scans: Check for misconfigured, publicly exposed cloud storage buckets referenced in exfiltration or data-leak cases.",
    "Traceroute Path Verification for Jurisdiction: Run a traceroute to a suspicious server to get a rough sense of its likely hosting jurisdiction before drafting an international legal request.",
    "Network Time Protocol (NTP) Drift Verification: Verify NTP synchronisation status on all devices whose logs are being correlated across a single timeline.",
    "IoT Device Network Log Extraction: Extract connection logs from smart-home or IoT devices (cameras, doorbells) that may have recorded relevant network or physical activity.",
    "Router Port-Forwarding Rule Audit: Audit port-forwarding rules on a compromised router to identify whether an attacker opened persistent remote-access channels.",
    "Malicious Redirect Chain Mapping: Map the full redirect chain of a phishing link from the initial short URL through every intermediate hop to the final landing page.",
    "DDoS Attack Source Log Aggregation: Aggregate source-IP logs from a DDoS incident to identify the botnet's approximate size and geographic spread for the case report.",
    "Public IP Geo-Location Caveat: Treat commercial IP-geolocation database results as approximate city/region-level only, never as a precise street address.",
    "Shared Hosting Multi-Tenant IP Caveat: Confirm whether a flagged IP hosts multiple unrelated websites (shared hosting) before attributing all activity on that IP to one target domain.",
    "SIP / VoIP Call Trace Requests: Request call-detail and routing logs from VoIP/SIP trunk providers when a fraud call originated from an internet-based calling service rather than a mobile SIM.",
    "Network Packet Timestamp Precision Checks: Verify the timestamp precision and time zone setting of a network capture tool before correlating it against telecom CDR timestamps.",
    "Reverse Image Search Verification: Run a suspect's profile or evidentiary photo through multiple reverse image search engines to detect stolen or stock-photo identity fraud.",
    "EXIF Metadata Extraction from Images: Extract EXIF metadata from an original (unshared) image file to recover capture device model, GPS coordinates and timestamp where present.",
    "Username Cross-Platform Correlation: Search a suspect's known username across multiple platforms to map their broader online footprint and possible aliases.",
    "Social Media Archive / Wayback Retrieval: Retrieve archived versions of a since-deleted or edited social media profile via web-archive services for evidentiary comparison.",
    "Geolocation from Background Landmarks: Identify landmarks, signage or terrain features visible in a photo/video to approximate the location where it was captured.",
    "Domain WHOIS History Timeline: Build a timeline of historical WHOIS records for a fraud domain to identify when it changed ownership or registrar.",
    "Public Court Record Cross-Check: Cross-check a suspect's name and known aliases against publicly available court record databases for prior related proceedings.",
    "Telegram Public Channel Monitoring: Monitor public Telegram channels known for circulating fraud scripts, stolen data dumps or scam recruitment posts relevant to active investigations.",
    "Business Registration Database Search: Search official company/business registration databases to verify whether a fraud scheme's claimed company actually exists and who its directors are.",
    "LinkedIn Employment History Verification: Cross-verify a suspect's claimed employment history on LinkedIn against actual employer confirmation, since profiles are self-reported and unverified.",
    "Google Dork Advanced Search Operators: Use targeted search operators (site:, filetype:, intitle:) to surface leaked documents or exposed pages relevant to an investigation.",
    "Metadata in Office Documents: Extract author, editing-history and revision metadata from Word/Excel/PDF documents circulated in a fraud scheme.",
    "Instagram/Facebook Graph Search Techniques: Use platform-native search techniques to map a suspect's mutual connections, tagged locations and group memberships.",
    "YouTube Video Geolocation and Timestamp Analysis: Analyse a video's visual cues, upload metadata and any embedded location tag to establish where and roughly when it was filmed.",
    "Cached Page Comparison for Edited Content: Compare cached/archived page snapshots against the live page to identify content a suspect edited or deleted after an incident.",
    "Public Data-Breach Database Cross-Reference: Cross-reference a victim's or suspect's email address against known public data-breach repositories to identify likely credential-exposure sources.",
    "Threat-Actor Handle Attribution via Forum History: Trace a threat actor's handle across cybercrime forums and marketplaces to build a behavioural and technical profile over time.",
    "QR Code Payload Decoding: Decode a suspicious QR code's embedded payload in a controlled, isolated environment before determining whether to visit the underlying link.",
    "Public Vehicle Registration Lookup: Cross-check a vehicle number appearing in case evidence (e.g., a scam collection agent's vehicle) against the public RTO database.",
    "Matrimonial Site Profile Verification: Cross-check photos and claimed details on a matrimonial fraud suspect's profile against reverse-image and other OSINT sources.",
    "Job-Portal Fake Listing Pattern Analysis: Analyse the posting pattern, contact details and payment-demand language of fraudulent job listings to link multiple postings to one operator.",
    "OSINT on Cryptocurrency Exchange Support Handles: Identify official versus impersonating social-media support handles for cryptocurrency exchanges cited in investment-fraud cases.",
    "Public Satellite Imagery Cross-Reference: Cross-reference satellite imagery timelines with a claimed alibi location or a fraud call-centre's suspected physical address.",
    "Group Chat Export Metadata Preservation: When lawfully obtaining a group chat export, preserve the full export file with metadata intact rather than screenshotting individual messages.",
    "Fake News / Deepfake Source-Tracing: Trace the earliest known appearance of a viral fake image, video or claim to identify the original source account or fabrication point.",
    "Public IP-to-Organisation WHOIS for Corporate Attacks: Use WHOIS/RDAP data on a corporate victim's network range to confirm the attack targeted the claimed organisation and not a shared hosting neighbour.",
    "Threat Intelligence Feed Cross-Referencing: Cross-reference a suspicious IP, domain or file hash against multiple open threat-intelligence feeds before drawing conclusions.",
    "Public Records for Shell Company Identification: Cross-check a suspected shell company's registered address against other companies registered at the same address to map a wider fraud network.",
    "Dark Web Marketplace Listing Documentation: Document dark-web marketplace listings relevant to a case with timestamped screenshots and the exact onion URL, taken from an isolated environment.",
    "Public Property Record Cross-Check: Cross-check property records tied to proceeds-of-crime investigations against a suspect's declared assets and known addresses.",
    "Social Engineering Script Pattern Library: Maintain a library of known scam-call and phishing-message scripts to quickly identify which known fraud template a new complaint matches.",
    "Public API Rate-Limit Aware OSINT Collection: Plan bulk OSINT queries against public APIs within their published rate limits to avoid getting the investigating account blocked mid-case.",
    "Corporate Email Format Pattern Guessing (Verification Only): Where a target company's email format pattern is already publicly known, use it only to verify a suspicious sender address's plausibility, not to guess unknown addresses for contact.",
    "News Archive Cross-Referencing for Suspect History: Search news archives for a suspect's name to uncover prior reported incidents, convictions or public complaints relevant to pattern-of-conduct evidence.",
    "Public Comment Section Behavioural Pattern Analysis: Analyse a suspect's public comment history across forums/YouTube for behavioural or motive-relevant statements.",
    "App Store Listing Metadata for Fraudulent Apps: Examine a fraudulent app's store listing metadata \u2014 developer account history, other published apps, review patterns \u2014 to map the wider operation.",
    "Public Domain Certificate Subject Alternative Name (SAN) Review: Review a domain's SSL certificate SAN field to discover other, related subdomains or domains registered under the same certificate.",
    "Investment-Scheme Website Clone Detection: Compare a suspected fraudulent investment website's structure and content against known legitimate platforms it may be cloning.",
    "Public Grievance-Portal Cross-Complaint Search: Search other public consumer-grievance portals for prior complaints against the same company/individual named in a cyber-fraud case.",
    "Telegram Bot Command Structure Analysis: Analyse a scam Telegram bot's command structure and response patterns to understand its automated fraud workflow.",
    "OSINT Framework Tool Selection Discipline: Select the specific OSINT tool matched to the data type needed (e.g., domain tools for infrastructure, people-search tools for identity) rather than one generic tool for everything.",
    "Public Academic/Research Paper Author Verification: Verify claimed academic credentials or research affiliations cited by a suspect in investment or expertise-based fraud cases.",
    "Cross-Reference of Scam Call-Centre Recruitment Ads: Cross-reference recruitment advertisements for 'BPO/calling job' postings against known call-centre-fraud recruitment patterns.",
    "Public Vehicle/Asset Auction Listing Cross-Check: Cross-check public auction listings for high-value assets against a suspect's declared income to support proceeds-of-crime lines of enquiry.",
    "SIM-Card Retailer KYC Pattern Analysis: Analyse the KYC pattern of SIM cards issued through a specific retailer to detect bulk-issuance fraud used for mule numbers.",
    "Screen-Recording of Live Fraud Website Behaviour: Screen-record a live fraudulent website's behaviour (fake countdown timers, fake payment gateways) as it appears in real time for evidentiary purposes.",
    "Public Social Media Group Membership Mapping: Map a suspect's membership across public groups relevant to the fraud type (e.g., trading-tips groups for investment fraud) to identify victim-sourcing channels.",
    "OSINT Verification Before Public Statement: Independently verify any OSINT-sourced claim through an official record before it is cited in a press briefing or public statement.",
    "Historical DNS Resolution Records (Passive DNS): Query passive DNS databases to see what IP addresses a malicious domain has resolved to over time, revealing hosting-infrastructure patterns.",
    "OSINT Corroboration Documentation Standard: Document the exact date, time, URL and method used for every OSINT finding cited in a case file, since online content changes or disappears.",
    "Email Header Full-Path Analysis: Analyse the complete raw email header (not just the client-displayed summary) to trace the true originating server of a phishing email.",
    "OAuth Token Grant Audit: Review third-party OAuth app grants on a compromised account to uncover silent persistence mechanisms that survive a password reset.",
    "Session Cookie Hijack Detection: Check for concurrent active sessions from unfamiliar devices/locations to detect session-cookie theft even where the password itself was never compromised.",
    "SIM-Swap Account Takeover Pattern: Recognise the pattern of a sudden network-loss complaint followed swiftly by unauthorised OTP-based account access as a SIM-swap indicator.",
    "Account Recovery Abuse Investigation: Investigate account-recovery logs (security questions, recovery email/phone changes) to establish exactly how an account was actually compromised.",
    "Two-Factor Bypass via SS7 Awareness: Be aware that SMS-based two-factor authentication can theoretically be bypassed via SS7-level interception in sophisticated cases, not only via SIM swap.",
    "Credential-Stuffing Attack Pattern Recognition: Recognise credential-stuffing attack signatures \u2014 many login attempts across many accounts using the same breached password list \u2014 in server logs.",
    "Password Manager Vault Forensic Extraction: Extract and, where legally authorised, decrypt password-manager vault files from a suspect's device to recover a full list of associated accounts.",
    "Business Email Compromise (BEC) Invoice-Fraud Pattern: Identify the specific BEC pattern where an attacker intercepts a genuine business email thread and alters bank account details on an invoice.",
    "Account Login-Location Anomaly Review: Review a compromised account's login-location history for geographically implausible sequential logins ('impossible travel').",
    "Social Media Account Recovery via Platform LEA Portal: Use the platform's dedicated law-enforcement request portal (rather than public 'forgot password' flows) to recover a hacked account for a victim.",
    "Email Forwarding Rule Backdoor Detection: Check a compromised email account for silently configured forwarding rules that continue leaking mail even after the visible password is reset.",
    "Password Reuse Risk Mapping via Breach Data: Where legally permissible, cross-reference a victim's exposed password from a known breach against other accounts to assess wider compromise risk.",
    "Fake Login Page (Phishing Kit) Structural Analysis: Analyse a captured phishing kit's file structure to identify the exfiltration endpoint where stolen credentials are actually being sent.",
    "Account Takeover via Recycled Phone Number: Investigate whether an account takeover exploited a recycled mobile number reassigned by the telecom operator to a new subscriber.",
    "Multi-Factor Authentication Fatigue Attack Recognition: Recognise 'MFA fatigue' attacks where a victim is bombarded with approval prompts until one is accidentally approved.",
    "Compromised WordPress/CMS Admin Panel Investigation: Investigate a compromised website's CMS admin-access logs to identify the entry point used before a defacement or malware injection.",
    "Account Deletion Request Legal-Hold Awareness: Place a legal-hold request with the platform before a suspect can exercise account/data deletion rights once an investigation is known to them.",
    "Cross-Account Correlation via Shared Device Fingerprint: Correlate multiple fraud accounts through shared device fingerprints (browser/device ID) even when different phone numbers and emails were used.",
    "Cloud Backup Account Compromise Scope Assessment: Assess the full scope of a compromised cloud-backup account (photos, contacts, documents) rather than just the initially reported concern.",
    "API Key / Developer Token Leak Detection: Search public code repositories for leaked API keys or tokens belonging to a victim organisation that enabled unauthorised access.",
    "Account Impersonation Takedown Request Drafting: Draft platform impersonation-takedown requests citing the specific policy clause violated, with side-by-side evidence of the fake versus genuine profile.",
    "Password Spray Attack Log Signature: Identify password-spray attack signatures \u2014 few attempts per account but across a very large number of accounts \u2014 distinct from credential stuffing.",
    "Digital Identity Aggregation for KYC Fraud Cases: Aggregate all digital-identity artefacts (Aadhaar-linked mobile, PAN-linked email, bank KYC photo) tied to a fraudulent account opening.",
    "Account Recovery Email Domain Typosquatting Check: Check whether an account's registered recovery email uses a typosquatted domain (e.g., gmial.com) as an indicator of a fraudulently created account.",
    "Session Token Replay Attack Investigation: Investigate whether a stolen session token was replayed from a different device/IP shortly after legitimate use, indicating live token theft.",
    "Third-Party Data Broker Opt-Out Verification for VIP Protection: For high-risk protectee cases, verify whether personal details have been scraped and listed on data-broker sites, feeding into a protection risk assessment.",
    "Fake Customer-Care Number Search-Engine Poisoning Detection: Identify fraudulent customer-care numbers planted via search-engine-optimised fake listings, a common vector for banking/wallet fraud.",
    "Account Security Question Predictability Assessment: When investigating an account takeover via security questions, assess whether the answers were publicly discoverable through the victim's own social media.",
    "Corporate Single Sign-On (SSO) Breach Scope Assessment: On a corporate breach involving SSO, assess every downstream application linked to the compromised identity provider, not just the initially affected system.",
    "Accessibility-Service Permission Audit: Inspect all apps holding active Accessibility Service permissions on a seized Android device to flag tools capable of scraping OTPs and screen content.",
    "Android ADB Logical Extraction: Perform a logical extraction via ADB on an unlocked, debugging-enabled Android device to recover app data without a full physical image.",
    "iOS Encrypted Backup Password Handling: Request the device owner's iTunes/Finder backup encryption password directly, since a forgotten password makes the encrypted backup effectively unrecoverable.",
    "WhatsApp Local Database (msgstore.db.crypt) Decryption: Decrypt a WhatsApp local database backup using the device-specific key to recover chat history, including from before an app reinstall.",
    "Deleted SMS/Call-Log Recovery via Physical Image: Recover deleted SMS and call-log entries from a physical image of the device's SQLite databases, even after in-app deletion.",
    "SIM Card Forensic Reading (ICCID/IMSI): Read a seized SIM card's ICCID and IMSI directly via a SIM reader to cross-verify against operator KYC and CDR records.",
    "Cloud Backup Correlation (Google/iCloud): Cross-reference a device's local data against its linked Google/iCloud backup to recover data no longer present locally.",
    "App-Specific Cache Forensics for Deleted Chats: Examine an app's cache and temporary-file directories for fragments of chat content deleted from the main database but not yet purged from cache.",
    "Mobile Device Jailbreak/Root Detection: Check whether a seized device has been jailbroken or rooted, since this affects both available extraction methods and potential evidence tampering by the user.",
    "GPS Location History Extraction from Apps: Extract historical GPS coordinates cached by mapping, ride-hailing or social apps to corroborate a suspect's or victim's movement timeline.",
    "SMS OTP Interception App Detection: Identify sideloaded apps configured to auto-forward incoming SMS to a remote number or server, a common OTP-theft technique.",
    "Mobile Banking App Session Log Analysis: Where legally obtained, analyse a mobile banking app's local session logs to establish device and time of a disputed transaction.",
    "Android Keystore / Biometric Lock Bypass Planning: Plan device-unlock strategy (PIN request, biometric consent, or forensic tool) based on the specific lock type before attempting any extraction.",
    "Contact List Cross-Referencing for Mule Networks: Cross-reference contact lists across multiple seized devices in a mule-account case to map the wider recruitment network.",
    "Call Recording App Data Extraction: Extract stored recordings from call-recording apps on a victim's or suspect's device relevant to threats, extortion or scam-call evidence.",
    "Telegram Secret Chat Limitation Awareness: Recognise that Telegram Secret Chats are device-local and end-to-end encrypted, meaning standard cloud data requests to Telegram will not recover their content.",
    "Mobile Malware/Spyware Static Triage: Perform static triage on a suspicious APK found on a victim's device (permissions requested, hardcoded C2 addresses) before deeper dynamic analysis.",
    "Device Clone Detection via IMEI/Baseband Mismatch: Cross-check a device's displayed IMEI against its baseband-reported IMEI to detect a cloned or IMEI-spoofed handset.",
    "UPI App Transaction Cache Extraction: Extract locally cached transaction history and linked-account details from UPI payment apps on a device involved in a financial-fraud case.",
    "Screen-Time / App-Usage Log Correlation: Correlate a device's screen-time and app-usage logs against the incident timeline to establish which app was actively in use at a given moment.",
    "Bluetooth Pairing History Extraction: Extract Bluetooth pairing history to identify other devices (headsets, other phones, vehicles) that a suspect's device has connected to.",
    "Mobile Device Physical Damage Documentation Before Extraction: Photograph and document any physical damage to a seized device before attempting any extraction, to explain later any extraction limitations.",
    "Dual-SIM / eSIM Profile Enumeration: Enumerate all active eSIM and physical SIM profiles on a seized device, since a suspect may operate a second undisclosed number entirely via eSIM.",
    "Third-Party Keyboard App Keylogging Risk Review: Check for third-party keyboard apps with excessive permissions that could function as a keylogger on a compromised device.",
    "WhatsApp Business API Fraud Account Investigation: Investigate a WhatsApp Business API account used in a fraud campaign by requesting the Business Solution Provider's onboarding KYC records.",
    "Mobile Device Airplane-Mode Preservation at Seizure: Place a seized device in airplane mode (or a Faraday bag) immediately at seizure to prevent remote wipe commands from reaching it.",
    "App Permission Timeline for Consent Disputes: Extract the historical permission-grant timeline for an app at the centre of a privacy or stalkerware complaint to establish when access was actually granted.",
    "Stalkerware App Detection and Removal Advisory: Identify commercial stalkerware apps disguised as system utilities during a device examination for a harassment or domestic-violence complaint.",
    "Mobile Device Time-Zone and Clock-Drift Verification: Verify the seized device's system clock and time zone setting against actual time at seizure, documenting any discrepancy before analysis.",
    "Encrypted Messaging App Metadata-Only Value: Recognise that even where message content is end-to-end encrypted and unrecoverable, connection and account-metadata requests to the provider can still be valuable.",
    "Blockchain Transaction Hash Documentation: Document the complete transaction hash, block number, asset type and exact transfer amount from the primary blockchain explorer for every hop traced.",
    "Wallet Clustering Heuristic Analysis: Apply wallet-clustering heuristics (common-input ownership, change-address patterns) to group addresses likely controlled by the same entity.",
    "Exchange KYC Request via Legal Process: Send a formal legal request to the cryptocurrency exchange where traced funds landed, seeking KYC details of the receiving account holder.",
    "Mixer / Tumbler Service Identification: Identify when traced funds have passed through a known mixing or tumbling service, breaking the direct on-chain trace.",
    "Stablecoin Issuer Freeze Request: Request the issuer of a stablecoin (where centrally controlled) to freeze specific flagged addresses holding traceable fraud proceeds.",
    "UPI-to-Crypto On-Ramp Trail Mapping: Map the trail from a victim's UPI payment through an on-ramp service into the first cryptocurrency wallet to establish the entry point of the fraud proceeds.",
    "Mule Account Layering Pattern Recognition: Recognise multi-hop mule-account layering patterns (rapid pass-through, similar transaction amounts) common in cyber-fraud money laundering.",
    "NFT Marketplace Wash-Trading Detection: Detect wash-trading patterns on NFT marketplaces used to artificially inflate value before a fraudulent sale to a victim.",
    "Crypto ATM Transaction Log Request: Request transaction and CCTV logs from crypto ATM operators where cash-to-crypto conversion is suspected in a laundering chain.",
    "Cross-Chain Bridge Transaction Tracing: Trace funds moved across a cross-chain bridge by matching the deposit transaction on the source chain to the corresponding mint/withdrawal on the destination chain.",
    "Dark-Web Marketplace Escrow Wallet Analysis: Analyse escrow wallet patterns on dark-web marketplaces to identify vendor-specific wallets used repeatedly across multiple listings.",
    "Investment-Fraud Smart Contract Analysis: Analyse a fraudulent investment scheme's smart-contract code for hardcoded owner-only withdrawal functions ('rug pull' mechanisms).",
    "Peer-to-Peer Crypto Trading Platform Chat-Log Request: Request chat logs and counter-party details from a P2P crypto trading platform where a scam sale/purchase occurred.",
    "Proceeds-of-Crime Attachment Under PMLA Coordination: Coordinate with the Enforcement Directorate where traced crypto or fiat proceeds exceed the threshold warranting PMLA action alongside the local cyber case.",
    "Crypto Wallet Seed-Phrase Seizure Protocol: Where lawfully seizing a physical note or device containing a wallet seed phrase, photograph it in place before any transfer and never type it into an internet-connected device.",
    "Exchange Transaction Timestamp Time-Zone Verification: Verify the time zone used in an exchange's provided transaction logs before correlating them against domestic CDR or bank timestamps.",
    "Stolen Crypto Asset Recovery Service Vetting: Vet any third-party 'crypto recovery service' a victim is approached by, since many such services are themselves a secondary scam.",
    "Blockchain Explorer API Rate-Limit Planning: Plan bulk on-chain tracing queries within a blockchain explorer API's rate limits to avoid throttling during a time-sensitive tracing operation.",
    "Crypto Exchange Suspicious Activity Report Cross-Reference: Cross-reference a case with any Suspicious Transaction Report an exchange may have already filed with FIU-IND for the same account.",
    "Multi-Signature Wallet Ownership Investigation: Investigate the co-signer structure of a multi-signature wallet involved in laundering to identify all parties who must jointly approve fund movement.",
    "Token Contract Verification for Counterfeit Coins: Verify a token's actual smart-contract address against the officially published contract to detect counterfeit tokens used in fraud.",
    "Crypto Exchange Cold-Wallet vs Hot-Wallet Freeze Distinction: Understand that funds moved into an exchange's cold-storage wallet may take longer to action on a freeze request than funds in an active hot wallet.",
    "Ransomware Ransom-Wallet Public Tracking: Track a ransomware campaign's published ransom wallet address publicly to monitor for victim payments and downstream fund movement.",
    "Crypto Donation Scam Wallet Pattern Recognition: Recognise reused wallet address patterns across multiple fake charity or disaster-relief donation scams following major news events.",
    "Layer-2 Network Transaction Tracing Awareness: Recognise when traced funds move onto a Layer-2 network (rollups, sidechains) requiring a different, network-specific explorer to continue tracing.",
    "IMEI Retrieval via Dialer Code: Dial *#06# on a physical handset to display all operational IMEI slots and serial identifiers for cross-verification against records.",
    "MAC Address Extraction for Network Attribution: Extract a device's Wi-Fi and Bluetooth MAC addresses from settings or firmware to support network-log correlation.",
    "Router Serial and Firmware Version Logging: Log the exact model, serial number and firmware version of a seized router, since vulnerabilities and log formats are firmware-specific.",
    "CCTV DVR/NVR Model-Specific Export Procedure: Identify the exact DVR/NVR model before attempting footage export, since export procedures and native file formats differ significantly across vendors.",
    "ATM/POS Terminal Transaction Log Request: Request transaction and maintenance logs directly from the bank/acquirer for a specific ATM or POS terminal implicated in card-skimming fraud.",
    "Skimming Device Physical Forensic Examination: Examine a recovered card-skimming device for stored data, embedded storage chips and any Bluetooth/GSM exfiltration module.",
    "Hardware Keylogger Physical Identification: Physically inspect keyboard cable connections for an inline hardware keylogger device during an on-site cyber-fraud scene examination.",
    "Vehicle Infotainment System Data Extraction: Extract paired-device history, call logs and navigation history from a vehicle's infotainment system relevant to a case timeline.",
    "Drone Flight-Log Extraction: Extract stored flight logs and associated controller-pairing data from a seized drone relevant to surveillance or smuggling cases.",
    "Smartwatch/Wearable Data Extraction: Extract activity, location and paired-phone data from a suspect's or victim's smartwatch, which can independently corroborate a movement timeline.",
    "Point-of-Sale Malware Physical Device Audit: Audit point-of-sale hardware for unauthorised firmware modifications or add-on skimming hardware in a suspected card-data-theft case.",
    "USB Device Serial-Number Correlation: Correlate a USB storage device's unique serial number against a computer's registry-logged USB connection history to prove that specific device was used.",
    "Biometric Attendance/Access Device Log Extraction: Extract entry/exit logs from a biometric attendance or access-control device to corroborate a suspect's physical presence claims.",
    "SIM Tray/Card Physical Damage Documentation: Photograph and document any physical damage or tampering to a SIM card/tray at the time of seizure, before any reading attempt.",
    "GPS Tracker Device Data Extraction: Extract stored location history directly from a physical GPS tracker device recovered in a stalking or vehicle-theft case.",
    "Ransomware Note Variant Identification: Match a ransomware note's exact wording and file-extension pattern against known threat-family databases to identify the specific variant.",
    "Phishing Kit Source-Code Exfiltration Endpoint Analysis: Analyse a seized phishing kit's PHP/JS source code to locate the hardcoded email address or Telegram bot token receiving stolen credentials.",
    "APK Static Analysis for Malicious Permissions: Statically analyse a suspicious APK's manifest file for excessive or unusual permission requests inconsistent with its claimed function.",
    "Memory Forensics for Fileless Malware: Perform live memory acquisition and analysis to detect fileless malware that leaves no trace on disk.",
    "Malware Command-and-Control Domain Sinkholing Awareness: Recognise that some malicious domains have already been sinkholed by security researchers, meaning connections to them no longer reach the original attacker.",
    "YARA Rule Application for Sample Triage: Apply established YARA rules against a suspicious file set to rapidly triage and classify samples by known malware family characteristics.",
    "Fuzzy Hashing for Malware Sample Similarity: Use fuzzy hashing (ssdeep-style) to identify near-identical malware samples that differ slightly from a known reference sample.",
    "Digital Signature Validity Check on Executables: Check whether a suspicious executable's digital signature is valid, revoked, or entirely absent as a first-pass triage step.",
    "Ransomware Negotiation Chat Log Preservation: Preserve the complete negotiation chat log with a ransomware group verbatim, including timestamps, as it may later corroborate attribution to a known group.",
    "Business Email Compromise Malware Attachment Triage: Triage attachments in suspected BEC/spear-phishing emails in an isolated sandbox before any user or investigator opens them on a live system.",
    "Log4Shell-Style Vulnerability Exploitation Trace Review: Review web-server access logs for known exploitation-string patterns when investigating breaches of systems running vulnerable third-party libraries.",
    "SQL Injection Attack Log Signature Recognition: Recognise SQL-injection attack signatures in web-server logs (unusual quote characters, UNION SELECT patterns) when investigating a data-breach complaint.",
    "Cross-Site Scripting (XSS) Payload Identification in Reports: Identify XSS payload patterns in user-submitted content when investigating a website-defacement or account-hijack complaint against a portal.",
    "Ransomware Payment Wallet Sharing Across Campaigns: Check whether a ransomware sample's embedded payment wallet address has appeared in other reported campaigns to establish possible group linkage.",
    "Deepfake Video Artefact Detection Checklist: Apply a structured checklist (unnatural blinking, edge artefacts, audio-lip sync mismatch) as an initial screen for suspected deepfake video evidence.",
    "Voice-Clone Audio Spectral Analysis: Apply spectral analysis to a suspected AI-voice-clone recording used in a fraud call to look for synthesis artefacts absent in natural speech.",
    "Container/Docker Environment Forensic Acquisition: Acquire forensic images of both the host and running containers when investigating a breach of a containerised server environment.",
    "Web Application Firewall Log Correlation for Attack Timeline: Correlate Web Application Firewall block/allow logs with backend application logs to build a complete picture of a web-based attack's progression.",
    "Encrypted Zip/RAR Archive Password Recovery Planning: Plan a proportionate password-recovery approach (dictionary attack using case-specific terms before brute force) for encrypted archives seized as evidence.",
    "Malicious Browser Extension Static Analysis: Statically analyse a suspicious browser extension's manifest and background script for data-exfiltration or ad-injection behaviour.",
    "Digital Arrest Scam Pattern Recognition: Recognise the 'digital arrest' scam pattern \u2014 a fake video call from someone posing as a law-enforcement or judicial officer coercing a victim into a bank transfer.",
    "AI Voice-Clone Emergency-Call Scam Awareness: Be alert to scam calls using AI-cloned voices of a victim's relative claiming a fabricated emergency to extract urgent money transfers.",
    "Deepfake Investment-Endorsement Scam Tracking: Track fraudulent investment advertisements using deepfake video of celebrities or officials endorsing fake trading platforms.",
    "QR Code Fraud Investigation Approach: Investigate QR-code payment-redirection fraud by treating the physical QR sticker itself as a seizeable exhibit at the point of complaint.",
    "Loan-App Harassment Case Data Extraction: Extract a predatory loan app's data-access permissions (contacts, gallery) to establish the basis for the harassment/blackmail complaint that followed.",
    "Sextortion Case First-Response Protocol: Follow the first-response protocol for sextortion complaints \u2014 reassure the victim, avoid re-victimising questioning, and prioritise rapid platform takedown requests.",
    "Fake Trading App Investment-Fraud Investigation Approach: Investigate fake trading-app fraud by first establishing whether the app itself was ever a real, registered platform or a wholly fabricated clone.",
    "Romance/Matrimonial Scam Cross-Border Coordination: Coordinate through Interpol/CBI channels when a romance-scam suspect is confirmed to be operating from outside India.",
    "Fake Government Scheme/Subsidy Scam Investigation: Investigate fraudulent SMS/calls impersonating government subsidy or scheme disbursement to identify the underlying phishing infrastructure.",
    "Courier/Parcel Scam Call-Centre Identification: Trace the calling number and script pattern in fake courier/customs-parcel scam calls to identify the operating call centre.",
    "Fake Tech-Support Pop-Up Scam Investigation: Investigate fake tech-support pop-up scams by preserving the exact pop-up page URL and any remote-access tool the victim was told to install.",
    "Job-Fraud Advance-Fee Scam Pattern Tracking: Track advance-fee job-fraud patterns (fake interview, fee for 'training kit' or 'security deposit') to link multiple victim complaints to one operator.",
    "Fake E-Commerce Website Takedown Coordination: Coordinate takedown of fake e-commerce websites collecting payment for goods never delivered, working with the hosting provider and payment gateway together.",
    "Synthetic Identity Fraud Detection in Loan/Account Applications: Recognise synthetic-identity fraud, where a fabricated identity combines a real document number with fabricated personal details, in loan or account-opening fraud cases.",
    "Gaming Platform In-App Currency Fraud Investigation: Investigate fraud involving stolen or fraudulently purchased in-game currency/items, coordinating with the gaming platform's dedicated fraud team.",
    "OTP-Fraud First 24-Hour Checklist: Follow the standard first-24-hour checklist for OTP fraud \u2014 1930 call confirmation, bank freeze request, CDR requisition and NCRP entry, in that order.",
    "Matrimonial Fraud Investigation Playbook: Follow the matrimonial-fraud playbook \u2014 verify the claimed profile's identity via OSINT, trace all fund transfers, and check for linked profiles on other matrimonial sites.",
    "Sextortion Investigation Playbook: Follow the sextortion playbook \u2014 immediate platform takedown request, preserve all messages/payment demands, and trace the payment or gift-card redemption trail.",
    "Fake Investment/Trading App Playbook: Follow the investment-fraud playbook \u2014 identify the app's actual developer/hosting, trace victim fund transfers to the first wallet/bank, and check for linked victim complaints nationally via NCRP.",
    "Digital Arrest Scam Investigation Playbook: Follow the digital-arrest playbook \u2014 preserve the video-call recording if available, trace the impersonated agency claim, and immediately pursue the fund-transfer trail.",
    "Loan-App Harassment Investigation Playbook: Follow the loan-app harassment playbook \u2014 extract the app's permission list, preserve all harassment messages sent to the victim's contacts, and trace the app's backend hosting.",
    "SIM-Swap Fraud Investigation Playbook: Follow the SIM-swap playbook \u2014 telecom port-out log request, bank transaction freeze, and identification of the fraudulent ID document used for the swap.",
    "Courier/Customs Parcel Scam Playbook: Follow the courier-scam playbook \u2014 preserve the calling number and script, trace any payment made, and check for matching complaints via script-pattern search.",
    "Fake Tech-Support Scam Playbook: Follow the tech-support scam playbook \u2014 identify the remote-access tool used, request its session logs from the vendor, and trace the payment demanded.",
    "Job-Fraud Advance-Fee Playbook: Follow the job-fraud playbook \u2014 trace the advance-fee payment, verify whether the claimed hiring company genuinely exists, and check for a wider victim pattern via the same contact details.",
    "Social Media Account Hacking Playbook: Follow the account-hacking playbook \u2014 use the platform's LEA portal for recovery, extract login/session logs, and check for a ransom or extortion demand tied to the hack.",
    "Morphed Image / Deepfake Harassment Playbook: Follow the morphed-image playbook \u2014 preserve the original and altered image side by side, identify the editing tool signature if possible, and pursue platform takedown alongside the criminal investigation.",
    "Cyberbullying/Online Harassment Playbook (Minor Victim): Follow the minor-victim harassment playbook \u2014 involve a child-welfare officer or counsellor from the first interview, and route platform requests through the child-safety-specific channel where available.",
    "Fake Government Subsidy Scam Playbook: Follow the subsidy-scam playbook \u2014 identify the phishing page's hosting, coordinate a public clarification with the genuine scheme's department, and trace the payment/data-collection trail.",
    "Cryptocurrency Investment Scam Playbook: Follow the crypto-investment-scam playbook \u2014 trace funds from the victim's fiat on-ramp through the first several wallet hops, and identify the exchange for a KYC request.",
    "Business Email Compromise (Vendor Fraud) Playbook: Follow the BEC playbook \u2014 preserve the full original email thread and headers, trace the altered bank details, and identify the point at which the thread was intercepted.",
    "Ransomware Attack on Local Business Playbook: Follow the ransomware playbook \u2014 preserve the ransom note and any negotiation contact, image affected systems before restoration, and check the strain against known decryptor databases.",
    "Data Breach / Leak Investigation Playbook: Follow the data-breach playbook \u2014 identify the exposed data's scope, trace the breach entry point via server logs, and assess mandatory breach-notification obligations for the affected organisation.",
    "Website Defacement Investigation Playbook: Follow the defacement playbook \u2014 preserve the defaced page's source and server logs before restoration, and trace the CMS/admin-panel entry point used.",
    "Fake Charity/Disaster-Relief Scam Playbook: Follow the fake-charity playbook \u2014 trace the payment/wallet used, verify against the genuine relief organisation's officially listed accounts, and issue a public alert where the scam is spreading widely.",
    "Online Gaming Platform Fraud Playbook: Follow the gaming-fraud playbook \u2014 coordinate with the platform's fraud team, establish actual real-money loss versus in-game value, and trace any real payment made to the scammer.",
    "Fake E-Commerce Non-Delivery Scam Playbook: Follow the fake-e-commerce playbook \u2014 trace the payment gateway transaction, identify the website's hosting and registrant, and check for a pattern of similar non-delivery complaints.",
    "Voice-Phishing (Vishing) Bank-Fraud Playbook: Follow the vishing playbook \u2014 trace the calling number (including VoIP/SIP origin where applicable), preserve the call recording if available, and pursue the fund-freeze request in parallel.",
    "WhatsApp/Telegram Impersonation Scam Playbook: Follow the impersonation playbook \u2014 preserve the fraudulent profile and chat, request the platform's account-creation IP/phone metadata via legal process, and trace any payment made.",
    "Fake Customer-Care Number Bank-Fraud Playbook: Follow the fake customer-care playbook \u2014 trace the fraudulent number's registration and any remote-access tool used, and coordinate with the bank on the fund trail.",
    "Sim-Box / International Call Fraud Playbook: Follow the SIM-box playbook \u2014 coordinate with the telecom operator to identify the physical SIM-box location via signal triangulation before a raid.",
    "Insider Data-Theft Investigation Playbook: Follow the insider-threat playbook \u2014 request the organisation's access logs, DLP alerts and exit-interview records for the departing/current employee under suspicion.",
    "Cyberstalking Investigation Playbook: Follow the cyberstalking playbook \u2014 build a chronological log of every contact/incident with preserved evidence for each, since a pattern of conduct is central to this offence.",
    "Fake Software/License Key Piracy Fraud Playbook: Follow the software-piracy-fraud playbook \u2014 trace the payment gateway used to sell counterfeit license keys and coordinate with the genuine software vendor's anti-piracy team.",
    "Cross-District Cyber-Fraud Syndicate Coordination Playbook: Follow the syndicate playbook \u2014 consolidate all linked FIRs across districts via CCTNS/Samanvaya before finalising individual chargesheets, to present the full network to the court."
];
